### ISSUE TITLE
confirmation microflow not called if primary returns false

### ISSUE THREAD

**Issue by Mcpoowl** [tieniber/ConfirmButton#1]
Hi Eric,

I've run in to a little snag and I was wondering if this was by design. Example case is that I check if a purchase is above $1k. So my primary microflow is:

`if $Expense/total > 1000 then true else false`

If I create an expense with a total of 1100, the confirmation shows and everything works as expected. However I'd expect that, if I create an expense with a total of 900, no confirmation is shown, but the microflow is executed anyway, this last bit does not work:

No confirmation is shown, but my microflow isn't executing either.

I'd like to use this widget as a extra check to notify the user, however when the user doesn't receive a confirmation (primary = false, I'd still like to execute the follow-up microflow)

**Comment by tieniber** [comment]
Hi Paul,

You can simply put your follow-up logic on the false branch of the first microflow. The true branch should just end, expecting the confirmation pop-up and optionally the follow-up microflow to handle any additional logic.

**Comment by Mcpoowl** [comment]
Wow, of course. I was thinking way to difficult. Thanks!
