### ISSUE TITLE
Widget does not work in IE 11

### ISSUE THREAD

**Issue by mysticagnostic** [tieniber/ConfirmButton#2]
See an error that reads:

> No constructor found for widget ConfirmButton.widget.ConfirmButton

Browser: IE ver 11.2312 and below

**Why it might be worth fixing:** most users in large enterprises continue to use IE 10+

**Comment by tieniber** [comment]
I'm having trouble reproducing this issue. For me, in both Windows 10 and Windows 7, the widget is working fine in IE11. Does this truly require an outdated version of IE11 to reproduce? I don't have a good way to test older builds of IE11.

Can you try this app for me and let me know if the widget works?
[https://confirmbuttontest.mxapps.io/](https://confirmbuttontest.mxapps.io/)

**Comment by tieniber** [comment]
@fractonaut, please let me know whether that test app works for you when you have a moment.

I suspect with so many widgets acting strangely for you in IE11 that there is some other issue going on.

**Comment by mysticagnostic** [comment]
I'm able to get your app to work in IE11. Seems like perhaps other widgets from the appstore might be causing this widget to break in my project. Thanks for your help!
